version: '3.9'
services:
  app:
    build: .
    environment:
      - DISPLAY=host.docker.internal:0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    runtime: nvidia
    command: ["/usr/app/venv/bin/python3", "./main.py"]