version: '3.9'

services:
  app:
    build: .
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}  # Para Linux e Windows
      - LIBGL_ALWAYS_SOFTWARE=1  # Renderização por software se não houver GPU
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mapeia o servidor X no Linux
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Usa GPU se disponível
    runtime: ${DOCKER_RUNTIME:-runc}  # Usa 'nvidia' se disponível, senão 'runc'
    command: ["/usr/app/venv/bin/python3", "./main.py"]  # Substitua pelo comando correto